### PR TITLE
Update README.md

### LINKED ISSUE #5: Update README.md
Readme still mentions pahal, as repo has its origin from pahal. update it to mention prodyogiki

### PR DESCRIPTION
**Pull request by Kazefiro**
Resolves #5

### CODE REVIEW

**Comment by rathod-sahaab** [comment]
Thanks, It only partially resolves #5  if you want to work on this you can get more details from https://istenith.com/Prodyogiki/
otherwise, I will be happy to merge your current PR.

**Comment by Kazefiro** [comment]
Oh I see, let me work a little more on it.

**Comment by Kazefiro** [comment]
That's the best I can do.

**Comment by rathod-sahaab** [comment]
Thankyou so much for your work on this ^-^

**Pull request merged**
